apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hydra-route
  namespace: hydra
  annotations:
    description: "Internal-only Hydra endpoints (JWKS, introspection) - not exposed externally"
spec:
  parentRefs:
  - name: eg-gateway
    namespace: envoy-gateway-system
    sectionName: internal  # Internal access only
  rules:
  # OIDC Discovery - internal only (Envoy Gateway fetches JWKS for JWT validation)
  - matches:
    - path:
        type: PathPrefix
        value: /auth/.well-known
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /.well-known
    backendRefs:
    - name: hydra-public
      port: 4444
  # Introspection - internal only (for backend services to validate tokens)
  - matches:
    - path:
        type: Exact
        value: /auth/oauth2/introspect
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /oauth2/introspect
    backendRefs:
    - name: hydra-public
      port: 4444
