apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  bootstrap:
    type: JSONPatch
    jsonPatches:
      # First create the empty array
      - op: add
        path: /bootstrap_extensions
        value: []
      # Then add the internal_listener extension to it
      - op: add
        path: /bootstrap_extensions/-
        value:
          name: envoy.bootstrap.internal_listener
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.bootstrap.internal_listener.v3.InternalListener
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: ClusterIP  # No cloud load balancer - use port-forward or ingress
      envoyDeployment:
        replicas: 2
        container:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
