# EnvoyPatchPolicy for true internal_listener (Phase 2)
# Uses in-process routing without kernel overhead
# Requires envoy.bootstrap.internal_listener extension enabled in EnvoyProxy bootstrap
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: internal-listener-patch
  namespace: envoy-gateway-system
  annotations:
    description: "Patches internal listener to use internal_listener (in-process, no kernel)"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: eg-gateway
  type: JSONPatch
  jsonPatches:
  # === LISTENER PATCHES ===
  # Remove socket address and add internal_listener
  - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
    name: "envoy-gateway-system/eg-gateway/internal"
    operation:
      op: remove
      path: "/address"
  - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
    name: "envoy-gateway-system/eg-gateway/internal"
    operation:
      op: add
      path: "/internal_listener"
      value: {}
  # === CLUSTER PATCHES ===
  # Convert EDS cluster to STATIC with envoy_internal_address endpoint
  - type: "type.googleapis.com/envoy.config.cluster.v3.Cluster"
    name: "httproute/envoy-gateway-system/forward-to-internal/rule/0"
    operation:
      op: replace
      path: "/type"
      value: "STATIC"
  - type: "type.googleapis.com/envoy.config.cluster.v3.Cluster"
    name: "httproute/envoy-gateway-system/forward-to-internal/rule/0"
    operation:
      op: remove
      path: "/eds_cluster_config"
  - type: "type.googleapis.com/envoy.config.cluster.v3.Cluster"
    name: "httproute/envoy-gateway-system/forward-to-internal/rule/0"
    operation:
      op: add
      path: "/load_assignment"
      value:
        cluster_name: "httproute/envoy-gateway-system/forward-to-internal/rule/0"
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                envoy_internal_address:
                  server_listener_name: "envoy-gateway-system/eg-gateway/internal"
