apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: tier2-daily-quota
  namespace: envoy-gateway-system
  annotations:
    description: "Tier 2 daily quota - 1000 requests per day per org"
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg-internal
  rateLimit:
    type: Global
    global:
      rules:
      # Daily quota per org (x-org-id header from JWT)
      # No IP fallback needed - unauthenticated requests are rejected at JWT validation
      - clientSelectors:
        - headers:
          - type: Distinct
            name: x-org-id
        limit:
          requests: 1000
          unit: Day
