apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: tier1-burst-limit
  namespace: envoy-gateway-system
  annotations:
    description: "Tier 1 burst rate limiting - tiered rps per client with IP fallback"
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: forward-to-internal
  rateLimit:
    type: Global
    global:
      rules:
      # Premium tier: 50 rps per client
      - clientSelectors:
        - headers:
          - name: x-tier
            value: premium
          - type: Distinct
            name: x-client-id
        limit:
          requests: 50
          unit: Second
      # Basic tier: 10 rps per client
      - clientSelectors:
        - headers:
          - name: x-tier
            value: basic
          - type: Distinct
            name: x-client-id
        limit:
          requests: 10
          unit: Second
      # Default (no tier or unknown): 5 rps per client
      - clientSelectors:
        - headers:
          - type: Distinct
            name: x-client-id
        limit:
          requests: 5
          unit: Second
      # Unauthenticated fallback: 5 rps per IP
      - clientSelectors:
        - sourceCIDR:
            type: Distinct
            value: "0.0.0.0/0"
        limit:
          requests: 5
          unit: Second
