# Service for routing from external listener to internal listener (same pods)
# Points to the gateway pods on port 8080 (internal listener)
apiVersion: v1
kind: Service
metadata:
  name: eg-gateway-internal
  namespace: envoy-gateway-system
  annotations:
    description: "Routes traffic from external listener to internal listener on same gateway"
spec:
  selector:
    gateway.envoyproxy.io/owning-gateway-name: eg-gateway
    gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
