apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api
  labels:
    app: go-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
    spec:
      containers:
      - name: go-rest-api
        image: davarski/go-rest-api-demo:latest
        ports:
        - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: go-rest-api-service
spec:
  selector:
    app: go-rest-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 10000
